### ISSUE TITLE
Is this real?

### ISSUE THREAD

**Issue by borghal** [ChristophWurst/twofactor_u2f#1]
Hi, 
I'm just wondering whether this plugin is actually working or just a dummy? How do I install and set it up? I'd really love to be able to use my Yubikey with nextcloud :-)

Cheers

**Comment by My1** [comment]
I would also wanna know how to use it. unlike the TOTP addon there's no release file that I can just kick right into the addon folder.

**Comment by MariusBluem** [comment]
You can try it out and report issues back to the issue tracker here ... I think it is currently some kind like WIP (Work in Progress) 😁 

...you may love to hear that U2F is on the Nextcloud 11 "official support" agenda (https://github.com/nextcloud/server/projects/1) which will be based on the work @ChristophWurst is doing here 😉

**Comment by borghal** [comment]
Great, Thanks for the heads-up. Guess I'll wait for NC 11 since I can't risk screwing up my production server with a WIP. Sorry I can't test it. But I will once it's a little more official. 

Keep up the great work!
